name: attendanceweb
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  flutter_riverpod: ^2.6.1
  uuid: ^4.5.1
  dio: ^5.8.0+1
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  shared_preferences: ^2.5.2
  flutter_spinkit: ^5.2.1
  email_validator: ^3.0.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  pdf: ^3.11.3
  printing: ^5.14.2
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

 